# This is a basic workflow to help you get started with Actions

name: Create a docker img

# Controls when the workflow will run
#on:
#  name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: python-helloworld
    - tag: latest
      run: docker build . --file Dockerfile -t python-helloworld

